apiVersion: v1
kind: Pod
metadata:
  name: toolbox
  namespace: kube-system
spec:
  containers:
  - name: toolbox
    image: ragnarb/toolbox:1.2
    imagePullPolicy: IfNotPresent
    args: ["sleep", "36500d"]
    #env:
    #- name: ROOK_ADMIN_SECRET
    #  valueFrom:
    #    secretKeyRef:
    #      name: rook-ceph-mon
    #      key: admin-secret
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /dev
      name: dev
    - mountPath: /sys/bus
      name: sysbus
    - mountPath: /lib/modules
      name: libmodules
    - mountPath: /mnt
        name: glusterfsvol
  volumes:
  - name: dev
    hostPath:
      path: /dev
  - name: sysbus
    hostPath:
      path: /sys/bus
  - name: libmodules
    hostPath:
      path: /lib/modules
  - name: glusterfsvol
    glusterfs:
      endpoints: glusterfs
      path: glusterfs
      readOnly: false