name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    # https://github.com/marketplace/actions/publish-docker
    - name: Define variables
      run: |
           echo "::set-env name=APP_RELEASE::$(cat RELEASE)"
      shell: bash
    - name: Publish to Registry ${{ env.APP_RELEASE }}
      run: echo "-------- ${{ env.APP_RELEASE }} -----------"
    - uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: ${{ github.repository }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: "latest,${{ env.APP_RELEASE }}"
